import { render } from "@workspace/transactional";
import WelcomeEmail from "@workspace/transactional/emails/generic";

const defaultContent = `Hey, \n\n Thank you for reaching out. I will get back to you as soon as I can.\n\nIn the meantime, feel free to explore my [website](https://somai.me) to learn more about my work and projects.\n\nLooking forward to connecting with you!\n`;

export const emailContent = async (content: string | null) =>
  await render(
    <WelcomeEmail
      content={content || defaultContent}
      footer="This message is generated by an AI assistant. It may not reflect the views of the recipient. Please verify any information before acting upon it. If you want to learn more, visit [https://somai.me/os](https://somai.me/os)."
    />
  );
